[semver]
current_version = '0.2.1'
last_stable_version = '0.2.1'
default_part = 'minor'
[semver.files."Cargo.lock"]
search = '''
[[package]]
name = "ohmyfpg"
version = "{current_version}"
'''
replace = '''
[[package]]
name = "ohmyfpg"
version = "{new_version}"
'''

[semver.prerelease]
bump_script = '''
var PREFIX = "dev.";
function bump(version) {
  var counter = !version.prerelease ? 0 : parseInt(version.prerelease.slice(PREFIX.length));
  return `${PREFIX}${counter + 1}`;
}
'''
