version: "3.9"
services:
  script:
    build:
      dockerfile: Dockerfile.performance
    ports:
      - "8000:5000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
